#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-joni
Version  : 2.1.2
Release  : 1
URL      : https://github.com/jruby/joni/archive/2.1.2.tar.gz
Source0  : https://github.com/jruby/joni/archive/2.1.2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar
Source2  : https://repo1.maven.org/maven2/org/jruby/joni/joni/2.1.2/joni-2.1.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-joni-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
joni
====
Java port of Oniguruma regexp library
## Usage
### Imports
```java
import org.jcodings.specific.UTF8Encoding;
import org.joni.Matcher;
import org.joni.Option;
import org.joni.Regex;
```

%package data
Summary: data components for the mvn-joni package.
Group: Data

%description data
data components for the mvn-joni package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar
/usr/share/java/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.pom
